### ISSUE TITLE
Setting property "classes" doesn't work

### ISSUE THREAD

**Issue by linnhk** [hunterliu1003/vue-final-modal#5]
Hi!

I've been trying to use this in my Vue project, but I ran into some problems when I tried setting the `classes` property to style the container. However, styling of the content by setting `contentClass` works fine.

I've added this module to my `main.js` like this:
```javascript
import { VueFinalModal } from 'vue-final-modal/lib';
Vue.component('VueFinalModal', VueFinalModal);
```
My component looks like this (I'm using Pug):
```pug
vue-final-modal(
	v-model="showModal"
	:classes="['modal-container']"
	:contentClass="['modal-content']"
)
```

My CSS for the container looks like this, for testing purposes:
```css
.modal-container {
	width: 50%;
	background-color: black;
}
```

The modal displayed has none of the attributes that I've tried to set. This is mostly an issue because I want to adjust the width of the modal. Do you know what might be the issue here?

**Comment by hunterliu1003** [comment]
Hi linnhk,

`Vue Final Modal`'s container has default style:

```
.vfm__container {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```

So set style `width: 50%` won't work.

In general usage, 

```pug
vue-final-modal(
    v-model="showModal"
    :classes="['modal-container']"
    :contentClass="['modal-content']"
)
```

```css
.modal-container {
    display: flex;
    justify-content: center;
    align-items:  center;
}

.modal-content {
    width: 50%;
    background-color: black;
}
```

I wrote an plain css example without using [tailwindCSS](https://tailwindcss.com/)
https://codepen.io/hunterliu1003/pen/ZEWoYeE

Hope the example solves your question.
